### ISSUE TITLE
Messages are not being displayed; they are just accumulating in sessions.

### ISSUE THREAD

**Issue by ehtesham-anwar** [php-flasher/php-flasher#187] opened 2024-06-28 18:29 UTC
Flash messages are being stored in the session but are not showing up on the screen. They keep getting added with each request. The messages are not being rendered to the user.
<img width="1064" alt="Screenshot 2024-06-28 at 7 29 28 PM" src="https://github.com/php-flasher/php-flasher/assets/70505941/215e8eb2-e651-4f3a-ac7b-d1c58aee5a7e">

**Comment by yoeunes** [comment] 2024-06-28 22:59
Hello @codebyshami,

Thank you for reporting this issue. Could you please provide a GitHub repository where I can reproduce the problem? Additionally, it would be helpful if you could share more details about the specific PHPFlasher version you are using and whether you are working within a framework.

Thank you!

Best regards,
Younes

**Comment by yoeunes** [comment] 2024-10-19 16:10
Hi @codebyshami,

I’m currently working on reducing the number of open issues to keep the project organized. Since I haven’t heard back on this issue for a while, I’ll be closing it for now.

If you’re still experiencing this problem, please update to the latest version of PHPFlasher. If the issue persists, feel free to reopen this issue or open a new one.

**Closed as completed by yoeunes** 2024-10-19 16:10 UTC
Labels: help wanted, findapr
