### ISSUE TITLE
Not working after update with symfony turbo stream

### ISSUE THREAD

**Issue by nassiry** [php-flasher/php-flasher#192] opened 2024-08-29 07:13 UTC
Hello Thanks for the symfony bundle, 
could you help me I'm using symfony version 6.4 and phpflasher 1.15 and updating the content via symfony ux-turbo in controller i'm returning the following code from controller without page refresh.

```php
flash()->addSuccess('Your product has been shipped.');

if (TurboBundle::STREAM_FORMAT === $request->getPreferredFormat()) {
    $request->setRequestFormat(TurboBundle::STREAM_FORMAT);

    return $this->renderBlock(
        'folder/_partial.html.twig',
        'success_stream', [
        'data' => $data
    ]);
}
```

but the message not displaying after update if I refresh/reload the page phpflasher display which is currently useless for me. as you can see I try to add flash message inside if statement and outside both fail.

**Comment by yoeunes** [comment] 2024-09-06 03:26
Hello @nassiry,

Thank you for using PHPFlasher—I hope it's serving you well!

Regarding your issue, it would be helpful if you could share a Symfony project on GitHub where I can suggest a more tailored solution. Based on what you've described, I can suggest the following approach:

Please note that this example has been tested with Symfony v7.1, but it should give you a clear idea of how to integrate flash notifications using Symfony UX-Turbo. Let me know if this helps or if you need further assistance!

### 1. Update `package.json`

In your `package.json`, add a new entry for PHPFlasher:

```json
"@flasher/flasher": "file:vendor/php-flasher/flasher/Resources",
```

Then run:

```bash
npm install --force
```

### 2. Create a JavaScript file

Create a new file, `assets/flasher.js`, with the following content to handle flash notifications dynamically:

```javascript
import flasher from "@flasher/flasher";

window.addEventListener("flasher:render", (event) => {
    const { options } = event.detail;

    flasher.render(options);
});
```

### 3. Include the new JS file

In your `assets/app.js`, import the `flasher.js` file:

```javascript
import "./flasher.js";
```

Then build your assets:

```bash
npm run build
```

### 4. Create a Trait

You can create a PHP trait to handle flash messages in your Live Components. Here's an example:

```php
<?php

declare(strict_types=1);

namespace App\Twig\Components;

use Symfony\UX\LiveComponent\ComponentToolsTrait;

use function Flasher\Prime\flash;

trait FlasherTrait
{
    use ComponentToolsTrait;

    protected function flash(?string $type = null, ?string $message = null, array $options = [], ?string $title = null): void
    {
        flash()->addFlash($type, $message, $options, $title);

        $this->dispatchFlasherEvent();
    }

    protected function dispatchFlasherEvent(): void
    {
        $data = flash()->render('json');

        $this->dispatchBrowserEvent('flasher:render', $data);
    }
}
```

### 5. Integrate the Trait into Your Component

Now, include the trait in your component and call the `flash` method. Here’s an example:

```php
<?php

declare(strict_types=1);

namespace App\Twig\Components;

use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Form\FormInterface;
use Symfony\UX\LiveComponent\Attribute\AsLiveComponent;
use Symfony\UX\LiveComponent\Attribute\LiveAction;
use Symfony\UX\LiveComponent\Attribute\LiveProp;
use Symfony\UX\LiveComponent\ComponentWithFormTrait;
use Symfony\UX\LiveComponent\DefaultActionTrait;

#[AsLiveComponent]
final class TopicUserForm extends AbstractController
{
    use DefaultActionTrait;
    use ComponentWithFormTrait;
    use FlasherTrait;

    #[LiveProp]
    public User $user;

    public function __construct(
        private readonly Security $security,
    ) {
    }

    public function mount(?User $user = null): void
    {
        $this->user = $user ?: $this->security->getUser();
    }

    protected function instantiateForm(): FormInterface
    {
        return $this->createForm(TopicUserType::class, $this->user);
    }

    #[LiveAction]
    public function save(EntityManagerInterface $em): void
    {
        $this->submitForm();

        $em->flush();

        $this->flash('success', 'Topics saved successfully.');
        $this->dispatchBrowserEvent('topic-modal:close');
    }
}
```

Let me know if this helps or if you need further assistance!
 
Younes

**Comment by nassiry** [comment] 2024-09-07 05:26
Hello thank you for your reply.

i'm using symfony 6.4 and also not using symfony ux live component .  and using webapp command. as

```
$ composer create-project symfony/skeleton:"6.4.*" my_project_directory
$ cd my_project_directory
$ composer require webapp

```



you can find the required files in zip i'm sure the same well work in symfony 7 without live component usage.
it's a simple todo displaying and creating.
all files are commented for better understanding.
[simple_todos.zip](https://github.com/user-attachments/files/16914651/simple_todos.zip)


call the migration command.  and start using by adding todos task.
if you have any more clarification please let me know.

**Comment by nassiry** [comment] 2024-09-14 12:58
Hello @yoeunes  any update status regarding this issue .

**Comment by yoeunes** [comment] 2024-09-21 02:47
Hi @nassiry,

First of all, sorry for the late response—I was quite busy recently. Thank you for sharing your code; I was able to reproduce the issue you're experiencing with PHPFlasher not displaying flash messages when using Symfony UX Turbo Streams.

I suggest the following solution to integrate PHPFlasher with Turbo Streams:

---

### **1. Create a Twig Extension**

Create a custom Twig extension that allows you to render the flash messages within your templates. Here's how you can do it:

```php
<?php

namespace App\Twig;

use Flasher\Prime\FlasherInterface;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

final class FlasherTwigExtension extends AbstractExtension
{
    private FlasherInterface $flasher;

    public function __construct(FlasherInterface $flasher)
    {
        $this->flasher = $flasher;
    }

    public function getFunctions(): array
    {
        return [
            new TwigFunction('flasher_render', [$this, 'render'], ['is_safe' => ['html']]),
        ];
    }

    /**
     * Renders the flash notifications.
     *
     * @param array  $criteria  Criteria to filter the notifications.
     * @param string $presenter The presenter format ('html', 'json', etc.).
     * @param array  $context   Additional context or options.
     */
    public function render(array $criteria = [], string $presenter = 'html', array $context = []): mixed
    {
        return $this->flasher->render($presenter, $criteria, $context);
    }
}
```

This extension provides a `flasher_render` Twig function that you can use to render flash messages within your templates.

---

### **2. Use the `flasher_render` Function in Your Turbo Stream Template**

In your `_todo_stream.html.twig` template, you can call the `flasher_render` function to render the flash messages:

```twig
{% block success_stream %}
    <turbo-stream action="append" target="todos_list">
        <template>
            <tr id="todo_{{ todo.id }}">
                <th scope="row">1</th>
                <td>{{ todo.task }}</td>
                <td>-</td>
                <td>-</td>
            </tr>

            {{ flasher_render() }}
        </template>
    </turbo-stream>
{% endblock %}
```

By including `{{ flasher_render() }}` inside the `<template>`, the flash messages will be rendered as part of the Turbo Stream response, allowing them to display without a full page refresh.

---

### **3. Update Your Controller**

Since you're using PHPFlasher **v1**, you should use `addSuccess()` instead of `success()` when adding flash messages in your controller:

```php
flash()->addSuccess('Task successfully created.');
```

This ensures that the flash message is properly added to the session and will be rendered when `flasher_render()` is called in your template.

---

I hope this helps resolve the issue! Let me know if you have any questions or need further assistance.

Best regards,

Younes

**Comment by yoeunes** [comment] 2024-10-19 16:10
Hi @nassiry,

I’m currently working on reducing the number of open issues to keep the project organized. Since I haven’t heard back on this issue for a while, I’ll be closing it for now.

If you’re still experiencing this problem, please update to the latest version of PHPFlasher. If the issue persists, feel free to reopen this issue or open a new one.

**Closed as completed by yoeunes** 2024-10-19 16:10 UTC
