### ISSUE TITLE
flash comes back if you navigate away and return back to the page again

### ISSUE THREAD

**Issue by sanzgrapher** [php-flasher/php-flasher#188] opened 2024-07-03 06:24 UTC
Laravel : phpflasher
I am using https://php-flasher.io/
for flash notification in laravel project.
and for add product to cart i am sending the falsh to show successful message
it works fine it shows up the flash notification
error : But teh flash Toast comes back if you navigate away and return back to the page again
is there any solution there.
![image](https://github.com/php-flasher/php-flasher/assets/101717917/5b3bba2a-aa41-4874-b051-20729f3b6200)

![image](https://github.com/php-flasher/php-flasher/assets/101717917/f4363cfe-2284-46d6-a9dd-dc7b7fdd3e94)

**Comment by yoeunes** [comment] 2024-07-03 09:02
Hi Narayan,

Thank you for using PHPFlasher and for reaching out with your issue. To better understand and debug the problem you're experiencing with the flash Toast notifications reappearing when navigating back to the page, could you please provide a bit more information?

1. Could you share a reproducer repository with a minimal setup that demonstrates the issue? This will help me investigate the problem more effectively.
2. Are there any specific steps or conditions under which the flash notifications reappear?
3. Which version of PHPFlasher and Laravel are you using?
4. Are there any custom configurations or additional code you’ve added related to flash notifications?

Your assistance in providing these details will be invaluable in helping me resolve this issue for you.

Looking forward to your response.

Best regards,  
Younes

**Comment by sanzgrapher** [comment] 2024-07-03 10:44
https://github.com/sanzgrapher/phpflash

please find the repo here i recreated : also follow the readme to recreat it
start the application
![image](https://github.com/php-flasher/php-flasher/assets/101717917/220906de-dcd8-4ddd-8601-ed097f4c838e)
click to any product
![image](https://github.com/php-flasher/php-flasher/assets/101717917/965e1f6a-3581-4e50-975e-d8f8ae03e9e2)
add to cart btn click and it loads the flash 
![image](https://github.com/php-flasher/php-flasher/assets/101717917/8da943c4-06c9-4296-bb4f-406e527376fb)
then click to back browser btn
![image](https://github.com/php-flasher/php-flasher/assets/101717917/e2019a63-fcd6-4979-abde-f4e24fdae328)
again teh popus loads
![image](https://github.com/php-flasher/php-flasher/assets/101717917/48e76a32-d141-4658-a2c6-2a39ab5d3a5f)
if we  click forward btn again it loads again the popup
![image](https://github.com/php-flasher/php-flasher/assets/101717917/e158f8fa-93ee-4990-a3d8-792eee927a69)

it loads on clicking fwd and bwd btn 
i dont know what did wrong here

**Comment by yoeunes** [comment] 2024-07-03 10:56
Hi Narayan,

Thank you for quickly providing the reproducer repository and the detailed steps to recreate the issue.

I will look into this tonight and get back to you with a solution or further questions if needed.

**Comment by sanzgrapher** [comment] 2024-07-03 13:42
Ok i will be waiting for it .

**Comment by sanzgrapher** [comment] 2024-07-04 03:37
is there anything we can do ?For this

**Comment by sanzgrapher** [comment] 2024-07-04 06:47
Is there any solution or any method to make this work ?

**Comment by yoeunes** [comment] 2024-07-04 10:14
Hi Narayan,

Thank you for your patience. I reproduced the problem you described. and I'm still investigating the issue to find a solution.

I will keep you updated on my progress and let you know as soon as I have a fix or a workaround.

**Comment by yoeunes** [comment] 2024-07-06 13:36
Hi Narayan,

I’ve investigated the issue, and I appreciate your detailed report and the reproducer repository. Here’s an explanation of the problem and a suggested workaround.

#### Issue Explanation

The behavior you’re experiencing with the flash Toast notifications reappearing when navigating back to the page is due to web browser caching, not an issue with PHPFlasher itself. 

When you hit the back button, the browser often displays a cached copy of the page you previously visited. This behavior is intended to make navigation faster by showing stored snapshots of pages. Consequently, the server does not get a chance to provide an updated version of the page, and any flash messages that were displayed initially may reappear.

This behavior is a default feature of some browsers and is not controlled by PHPFlasher. For example, if you navigate to the Profile page using the navigation bar instead of the back button, you will not see the flash message again, as the server provides a fresh response.

#### Workaround

To mitigate this behavior, I’ve created a PR https://github.com/sanzgrapher/phpflash/pull/1 that introduces middleware to prevent browsers from caching pages by adding appropriate headers to the HTTP response. This ensures that the browser does not show stale content when navigating back.

### Middleware Implementation

Here’s the implementation of the `NoCacheHeaders` middleware:

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class NoCacheHeaders
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        $response = $next($request);

        return $response
            ->header('Cache-Control', 'no-cache, no-store, max-age=0, must-revalidate')
            ->header('Pragma', 'no-cache');
    }
}
```

### Registration in `bootstrap/app.php`

The middleware is registered globally to apply these headers to all routes:

```php
$middleware->web(App\Http\Middleware\NoCacheHeaders::class);
```

### Conclusion

This middleware acts as a workaround to ensure that flash messages do not reappear when using the browser's back button by preventing the caching of responses. While this is not a PHPFlasher-specific issue, this solution provides a consistent experience by controlling the browser's cache behavior.

**Comment by RehamTammam1** [comment] 2024-08-22 11:16
Here’s the comment formatted appropriately for GitHub:

---

Hello @yoeunes,

I followed the provided solution, but unfortunately, the issue still persists. Here’s what I did:

1. **Updated the `Kernel.php` File:**

```php
<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \App\Http\Middleware\TrustProxies::class,
        \App\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \Flasher\Laravel\Middleware\FlasherMiddleware::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            \App\Http\Middleware\NoCacheHeaders::class, // Added middleware
        ],

        'api' => [
            'throttle:60,1',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
}
```

2. **Created the `NoCacheHeaders` Middleware:**

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class NoCacheHeaders
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        $response = $next($request);

        return $response
            ->header('Cache-Control', 'no-cache, no-store, max-age=0, must-revalidate')
            ->header('Pragma', 'no-cache');
    }
}
```

Despite these changes, the issue where flash notifications reappear when navigating back to the previous page still persists. Any guidance on what I might be missing or additional troubleshooting steps would be greatly appreciated!

**Comment by yoeunes** [comment] 2024-08-22 11:49
Hi Reham,

Thank you for sharing the details and the steps you've taken so far. It seems like the issue might be more specific to your application setup. To help me better understand and troubleshoot the problem, could you please create a GitHub repository where I can reproduce the issue? If you could also provide the exact steps to reproduce the problem, that would be very helpful.

**Comment by RehamTammam1** [comment] 2024-08-22 11:57
Hello @yoeunes,
Thank you for the quick reply.
I’ve uploaded the most up-to-date version of my projects. Please find the details below:
https://github.com/RehamTammam1/RoRoSchool

Steps to Reproduce:
Log in to the application.
Navigate to http://school.test/ar/grades.
Additionally, I’ve recorded a quick video demonstrating the issue. You can view it here: https://screenrec.com/share/QHcnfiGPbF.

Feel free to reach out if you need further details or clarification.

Best regards,

**Comment by yoeunes** [comment] 2024-08-22 12:24
Hi Reham,

Thanks for sharing the repository and the video, both were very helpful.

I took a look at your code, and I believe the issue is due to the placement of the `FlasherMiddleware`. Instead of adding it to the global middleware stack, it should be placed within the `web` middleware group.

Here’s the change I suggest:

```php
<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        // \App\Http\Middleware\TrustHosts::class,
        \App\Http\Middleware\TrustProxies::class,
        \App\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        // \Flasher\Laravel\Middleware\FlasherMiddleware::class, // Remove from here
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            \Flasher\Laravel\Middleware\FlasherMiddleware::class, // Add here
            \App\Http\Middleware\NoCacheHeaders::class,
        ],

        'api' => [
            'throttle:60,1',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];

    //...
}
```

Could you please apply this change and test it on your side? Let me know if it resolves the issue.

Looking forward to your feedback!

Best regards,  
Younes

**Comment by RehamTammam1** [comment] 2024-08-22 12:29
Hi @yoeunes ,

Thank you for your response and the suggestion. I’ve updated the middleware placement as you recommended, and it has resolved the issue!

I appreciate your help with this. Everything is working perfectly now.

Best regards,

**Comment by yoeunes** [comment] 2024-09-22 16:12
Hi @sanzgrapher and @RehamTammam1,

Since the issue has been addressed, I’ll close it for now. If you encounter any further problems or have additional questions, please feel free to reopen this issue or create a new one.

Thanks.

**Closed as completed by yoeunes** 2024-09-22 16:12 UTC
Labels: help wanted, findapr
