### ISSUE TITLE
Compatible with Symfony 7.0?

### ISSUE THREAD

**Issue by frdemoulin** [php-flasher/php-flasher#162] opened 2023-11-30 20:37 UTC
Hello,

Just upgraded my Symfony project to 7.0. I'm using PHPFlasher 1.15.3, but when I try composer install, I get the message:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-flasher/flasher-symfony[v1.15.0, ..., v1.15.3] require symfony/console ^2.0 || ^3.0 || ^4.0 || ^5.0 || ^6.0 -> found symfony/console[2.0.4, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.49, v5.0.0, ..., v5.4.32, v6.0.0, ..., v6.4.0] but it conflicts with your root composer.json require (7.0.*).
    - Root composer.json requires php-flasher/flasher-symfony ^1.15 -> satisfiable by php-flasher/flasher-symfony[v1.15.0, v1.15.1, v1.15.2, v1.15.3].
```

Is PHPFlasher compatible with Symfony 7.0?

Regards,
Fred

**Comment by ToshY** [comment] 2023-12-09 15:28
Apparently @yoeunes is busy with it in #163, so we'll just have to be patient 😉

**Comment by yoeunes** [comment] 2023-12-09 18:30
Hello @frdemoulin and @ToshY,

I've just released PHPFlasher v1.15.4 with support for Symfony 7.0. It's not fully tested yet, so I'd appreciate if you could test it in your environment. Please update using:

```bash
composer require php-flasher/flasher-symfony ^1.15.4
```

Let me know if there are any issues. Your feedback will help in deciding whether to close this issue.

Thanks!
Younes

**Comment by ToshY** [comment] 2023-12-23 18:55
Hey @yoeunes 👋 

I can't exactly test it properly until other dependencies in my project support Symfony 7 🙁. I will test it when I'm able to. In the meantime, maybe @frdemoulin could check if it works.

**Comment by frdemoulin** [comment] 2023-12-25 17:00
Hello,

I've just updated a project to Symfony 7.0.1. For the moment, I don't see
any problem with php-flasher. Great!

Regards,
Fred

**Comment by yoeunes** [comment] 2023-12-25 17:04
Thanks guys 🙏🏼

**Comment by yoeunes** [comment] 2024-09-22 15:40
Hi @frdemoulin @ToshY,

Since you’ve confirmed that PHPFlasher works with Symfony 7, I’ll close this issue.

If you encounter any problems, feel free to reopen it or create a new one.

Thanks.

**Closed by yoeunes** 2024-09-22 15:40 UTC
